<a href="https://colab.research.google.com/github/ngkokjoe-create/data-science-toolkit/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

1. Find some real dataset. Load it on Colab, Kaggle etc. Try to visualize some of it

In [12]:
df = pd.read_csv('/content/drive/MyDrive/AI_Usage_and_Impact_on_Students_and_Professionals.csv')
display(df)

,User_ID,Age,User_Type,Education_Level,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Accuracy_Rating,Satisfaction_Score,Would_Recommend
0,U0269,30.0,Professional,Master's,ChatGPT,Office Work,2.0,4.0,7.0,Yes
1,U0217,30.0,Professional,Bachelor's,ChatGPT,Customer Support,5.7,3.0,9.0,Yes
2,U0152,17.0,Student,NaN,Chat GPT,Coding,1.0,2.0,4.0,No
3,U0264,35.0,Professional,Bachelor's,Meta AI,Coding,1.7,4.0,5.0,Maybe
4,U0263,19.0,Student,Undergraduate,Perplexity AI,NaN,4.1,4.0,7.0,Yes
...,...,...,...,...,...,...,...,...,...,...
295,U0066,NaN,Professional,Bachelor's,Microsoft Copilot,NaN,1.8,3.0,4.0,No
296,U0094,43.0,Professional,Diploma,ChatGPT,Content Creation,1.2,3.0,NaN,No
297,U0136,48.0,Professional,Diploma,Google Gemini,Coding,5.5,4.0,7.0,Yes
298,U0002,31.0,Professional,Diploma,ChatGPT,Coding,0.7,3.0,4.0,No
299,U0130,36.0,Professional,Diploma,Chat GPT,Coding,2.8,4.0,7.0,Yes

2. Evaluate if the data is good or not. Does it have enough samples?

    -My dataset is good and it have enough samples because it has a large sample size.

3. How many features does it have? Is it enough?

    -It have 10 features and it is enough for analysis,which provide different information for analysis.

4. How many samples/observation does it have? Is it enough?

    -My dataset has 300 samples, as confirmed by checking the number of rows in dataset and it is enough for basic data analysis.

In [17]:
print(f"My dataset contains {df.shape[0]} samples")

My dataset contains 300 samples

5. What are the datatypes does the dataset consist of?

In [18]:
print(df.dtypes)

User_ID                    object
Age                       float64
User_Type                  object
Education_Level            object
AI_Tool                    object
AI_Purpose                 object
AI_Usage_Hours_Per_Day    float64
Accuracy_Rating           float64
Satisfaction_Score        float64
Would_Recommend            object
dtype: object

6. How many columns have null values? If yes, which column, which rows

In [32]:
print(df.isnull().sum())

pd.set_option('display.max_rows', None)
null_locations = df.isnull().stack()
display(null_locations[null_locations])

User_ID                    0
Age                       23
User_Type                  0
Education_Level           13
AI_Tool                   11
AI_Purpose                13
AI_Usage_Hours_Per_Day     7
Accuracy_Rating           15
Satisfaction_Score         7
Would_Recommend            5
dtype: int64

2    Education_Level           True
4    AI_Purpose                True
24   Education_Level           True
29   Age                       True
     Education_Level           True
30   Accuracy_Rating           True
31   AI_Purpose                True
33   AI_Tool                   True
37   AI_Tool                   True
40   Would_Recommend           True
48   AI_Usage_Hours_Per_Day    True
49   Age                       True
51   Satisfaction_Score        True
52   Age                       True
58   AI_Purpose                True
60   AI_Usage_Hours_Per_Day    True
69   Accuracy_Rating           True
72   AI_Tool                   True
73   AI_Purpose                True
74   Age                       True
76   AI_Tool                   True
78   Age                       True
80   Accuracy_Rating           True
81   AI_Tool                   True
88   Satisfaction_Score        True
93   Would_Recommend           True
94   Education_Level           True
     AI_Usage_Hours_Per_Day    True
95   Age                       True
     Accuracy_Rating           True
96   Age                       True
106  Would_Recommend           True
110  Would_Recommend           True
112  AI_Purpose                True
113  AI_Tool                   True
122  Satisfaction_Score        True
123  Age                       True
125  AI_Purpose                True
     Accuracy_Rating           True
126  AI_Tool                   True
127  AI_Purpose                True
128  Satisfaction_Score        True
131  Education_Level           True
132  Education_Level           True
142  AI_Purpose                True
143  Would_Recommend           True
151  Age                       True
159  Education_Level           True
160  AI_Purpose                True
161  AI_Tool                   True
162  Satisfaction_Score        True
165  AI_Purpose                True
     Accuracy_Rating           True
166  Age                       True
168  AI_Purpose                True
169  Education_Level           True
171  Accuracy_Rating           True
174  AI_Usage_Hours_Per_Day    True
175  Accuracy_Rating           True
179  Accuracy_Rating           True
182  Education_Level           True
183  AI_Purpose                True
186  Accuracy_Rating           True
188  Education_Level           True
194  Age                       True
207  Age                       True
     AI_Tool                   True
213  Age                       True
218  Age                       True
220  Age                       True
222  Age                       True
232  Age                       True
233  Age                       True
236  Age                       True
239  Age                       True
242  Education_Level           True
247  Accuracy_Rating           True
248  Accuracy_Rating           True
249  AI_Usage_Hours_Per_Day    True
250  Satisfaction_Score        True
251  AI_Tool                   True
252  AI_Usage_Hours_Per_Day    True
262  Accuracy_Rating           True
263  Age                       True
264  Age                       True
270  AI_Usage_Hours_Per_Day    True
271  Education_Level           True
276  Accuracy_Rating           True
280  AI_Tool                   True
281  Education_Level           True
282  Accuracy_Rating           True
295  Age                       True
     AI_Purpose                True
296  Satisfaction_Score        True
dtype: bool

7. Which column is the feature, which is the target output?

    -{User_ID,	Age,	User_Type,	Education_Level,	AI_Tool,	AI_Purpose,	AI_Usage_Hours_Per_Day,	Accuracy_Rating and	Satisfaction_Score} are the features, while Would_Recommend is the target output.

8. Does it have missing values? If yes, which column, which row.

    -Yes, it has missing values, which are identified in Question 6.

9. What kind of question can be asked, should we ask. Does the dataset suits the question we are asking?

    -We can ask which AI tool is most recommended. My dataset suits this question because it contains information about AI_Tool, hours of AI usage, accuracy ratings, satisfaction scores, and whether users would recommend the AI tool.